// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const supportSidebars = {
  supportSidebar: [
    [{type: 'autogenerated', dirName: '.'}],
  ],
};

export default supportSidebars;
